# Training parameters
training:
  steps: 25_000_000
  n_envs: 16

# Model Hyperparameters
model:
  learning_rate:
    initial: 0.0001
    minimum: 0.000001
  entropy_coefficient:
    initial: 0.05
    final: 0.001
    decay_fraction: 0.3

# Network Architecture
network:
  policy: [256, 256]
  value: [256, 256]

# Logging and Saving
paths:
  log_name: "Jaipur_tb"
  # save_name can be set here or generated automatically
  save_name: null 